@startuml
set separator none
'hide members
'hide namespace creation

!define custom(value) <color:red>value</color>
!define computed(value) <color:green>value</color>
!define related(value) <color:purple>value</color>
!define descr(value) <color:gray><i>value</i></color>

skinparam defaultFontName "Roboto"
skinparam TitleFontName "Roboto"
skinparam TitleFontSize 25
skinparam ArrowFontName "Roboto"
skinparam ArrowFontColor Grey
'skinparam SameClassWidth True
skinparam ClassStereotypeFontColor Maroon
skinparam ClassStereotypeFontStyle Bold, Italic
skinparam ClassFontColor Blue
skinparam ClassFontStyle Bold

title Product
footer Odoo v17

class product.template <<Product>> {
   +id: integer
   --
   +company_id: [[res.company]]
   +categ_id: [[product.category]] (required)
   +currency_id: [[res.currency]]
   +cost_currency_id: [[res.currency]]
   +product_brand_id:  [[product.product_brand]]
   +uom_id: [[uom.uom]]
   +uom_po_id: [[uom.uom]]
   +product_variant_id: [[product.product]]
   --
   +active: boolean
   +color: integer
   +price: float
   +list_price: float
   +computed(standard_price: float)
   +volume: float
   +weight: float
   +sale_ok: boolean
   +purchase_ok: boolean
   +is_product_variant: boolean = [[False]]
   +service_policy: (ordered_timesheet, delivered_timesheet, delivered_manual)
   +service_type: (manual, timesheet)
   +detailed_type: ([[consu]], service)
   +type: (consu, service)
   +priority: ([['0']], '1')
   +barcode: char
   +state: char
   +description: char
   +description_purchase: char
   +description_sale: char
   +sequence: integer
   +image_1920: image [[image.mixin]]
   --
   *product_variant_ids: [[product.product]]
   *attribute_line_ids: [[product.template.attribute.line]]
   *valid_product_template_attribute_line_ids: [[product.template.attribute.line]]
   *seller_ids: [[product.supplierinfo]]
   *variant_seller_ids: [[product.supplierinfo]]
   *packaging_ids: [[product.packaging]]
}

class product.category {
   +id: integer
   --
   +child_id: [[product.category]]
   +parent_id: [[product.category]]
   --
   +name: char
   +complete_name: char
   +parent_path: char
}

class product.product <<Product Variant>> {
   +id: integer
   --
   +product_tmpl_id: [[product.template]] (required)
   +base_unit_id: integer
   --
   +active: boolean
   +product_search_code: varchar
   +is_product_variant: boolean = [[True]]
   +barcode: char
   +combination_indices: varchar
   +default_code: char
   +volume: float
   +weight: float
   +base_unit_count: float
   +fix_price: float
   +variant_desc: text
   +image_variant_1920: image
   +standard_price: float
   --
   *product_template_attribute_value_ids: [[product.template.attribute.value]]
   *product_template_variant_value_ids: [[product.template.attribute.value]]
   *barcode_ids: [[product.multi.barcode]]
}

class product_variant_combination {
  +product_product_id: [[product.product]]
  +product_template_attribute_value_id: [[product.template.attribute.value]]
}

class product.attribute {
   +id: integer
   --
   +name: char
   +create_variant: ([[always]], dynamic, no_variant)
   +display_type: ([[radio]], pills, select, color)
   --
   *value_ids: [[product.attribute.value]]
   *attribute_line_ids: [[product.template.attribute.line]]
   *product_tmpl_ids: [[product.template]]
}

class product.attribute.value {
   +id: integer
   --
   +name: char
   +sequence: integer
   +is_custom: boolean
   +html_color: char
   +color: integer
   --
   +attribute_id: [[product.attribute]]
   --
   *pav_attribute_line_ids:  [[product.template.attribute.line]]
}

class product.template.attribute.line {
   +id: integer
   --
   +active: boolean
   +value_count: integer (product.attribute.value)
   --
   +product_tmpl_id: [[product.template]]
   +attribute_id: [[product.attribute]]
   --
   *value_ids: [[product.attribute.value]]
   *product_template_value_ids: [[product.template.attribute.value]]
}

class product.template.attribute.value {
   +id: integer
   --
   +color: integer
   --
   +attribute_line_id: [[product.template.attribute.line]]
   +product_attribute_value_id: [[product.attribute.value]]
   +product_tmpl_id: [[product.template]]
   +attribute_id: [[product.attribute]]
}

class product.supplierinfo <<Pricelist Supplier>>{
   +id: integer
   --
   +product_code: char
   +product_name: char
   +display_name: char
   +price: float
   +min_qty: integer
   +sequence: integer
   +date_start: date
   +date_end: date
   +delay: integer
   --
   +name: [[res.partner]]
   +company_id: [[res.company]]
   +currency_id: [[res.currency]]
   +product_id: [[product.product]]
   +product_tmpl_id: [[product.template]] descr(always assigned)
}

class product.packaging{
  +id: integer
  --
  +product_id: [[product.product]]
  +company_id: [[res.company]]
  +packaging_type_id: [[product.packaging_type]]
  --
  +sequence: integer
  +barcode: varchar
  +qty: integer
 }

class product.pricelist{
    +id: integer
    --
    +currency_id: [[res.currency]]
    +company_id: [[res.company]]
    --
    +name: char
    +active: boolean
    +sequence: integer = [[16]]
    +discount_policy:
    (with_discount, without_discount)
}

class product.pricelist.item{
    +id: integer
    --
    +product_tmpl_id: [[product.template]]]
    +product_id: [[product.product]]
    +categ_id: [[product.category]]]
    +base_pricelist_id: [[product.pricelist]]
    +pricelist_id: [[product.pricelist]]
    +company_id: [[res.company]]
    +currency_id:  [[res.currency]]
    --
    +active: boolean
    +computed(name: char)
    +date_start: datetime
    +date_end: datetime
    +min_quantity: float
    +applied_on:
    ([[3_global]], 2_product_category, 1_product, 0_product_variant)
    +base:(list_price,standard_price,pricelist)
    +price_surcharge: float
    +price_discount: float
    +price_round: float
    +price_min_margin: float
    +price_max_margin: float
    +fixed_price: float
    +percent_price: float
}

class mrp.bom{
    +id: integer
    --
    +product_tmpl_id: [[product.template]]
    +product_id: [[product.product]]
    --
    +product_qty: float
    +product_uom: [[product.uom]]
    +product_uom_qty: float
    +product_uom: [[product.uom]]
    +routing_id: [[mrp.routing]]
    +type: (normal,phantom,sub_products)
    --
    +bom_line_ids: [[mrp.bom.line]]
}

class mrp.bom.line{
    +id: integer
    --
    +product_tmpl_id: [[product.template]]
    +product_id: [[product.product]]
    +bom_id: [[mrp.bom]]
    --
    +product_qty: float
    +product_uom: [[product.uom]]
    +product_uom_qty: float
    +product_uom: [[product.uom]]
}

class res.partner <<Vendor>>{
    +id: integer
}

class res.currency{
   +id: integer
}

class res.company{
   +id: integer
}

product.category o-- product.category: parent_id
product.category o-- product.category: child_idna

product.product o-- product.template: product_tmpl_id
product.product o-- product.category: categ_id

product.attribute.value o-- product.attribute: attribute_id

product_variant_combination o-- product.product: product_product_id
product_variant_combination o-- product.template.attribute.value: product_template_attribute_value_id

product.template.attribute.value o-- product.template: product_tmpl_id
product.template.attribute.value o-- product.attribute.value: product_attribute_value_id
product.template.attribute.value o-- product.attribute: attribute_id

product.template.attribute.line o-- product.template: product_tmpl_id
product.template.attribute.line o-- product.attribute: attribute_id
product.template.attribute.line -- product.attribute.value: value_ids/pav_attribute_line_ids
product.template.attribute.line -- product.template.attribute.value

product.template o-- product.category: categ_id
product.template o-- product.product_brand: product_brand_id

product.pricelist o-- res.currency: currency_id
product.pricelist o-- res.company: company_id

product.pricelist.item o-- product.pricelist: pricelist_id/base_pricelist_id
product.pricelist.item o-- product.template: product_tmpl_id
product.pricelist.item o-- product.product: product_id
product.pricelist.item o-- res.company: company_id
product.pricelist.item o-- res.currency: currency_id

product.template.attribute.value o-- product.template.attribute.line: attribute_line_id

product.packaging o-- product.product: product_id

product.supplierinfo o-- product.product: product_id
product.supplierinfo o-- product.template: product_tmpl_id
product.supplierinfo o-- res.partner: name

mrp.bom o-- product.product: product_id
mrp.bom o-- product.template: product_tmpl_id

mrp.bom.line o-- mrp.bom: bom_id
mrp.bom.line o-- product.product: product_id
mrp.bom.line o-- product.template: product_tmpl_id

@enduml